<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Errors;

class AlreadyCanceledSubscription1Throwable extends \RuntimeException
{
    public AlreadyCanceledSubscription1 $container;

    public function __construct(string $message, int $statusCode, AlreadyCanceledSubscription1 $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}