<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Errors;

class ManualRetryLimitExceededThrowable extends \RuntimeException
{
    public ManualRetryLimitExceeded $container;

    public function __construct(string $message, int $statusCode, ManualRetryLimitExceeded $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}