<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Errors;

class OrderNotEligibleForInvoiceThrowable extends \RuntimeException
{
    public OrderNotEligibleForInvoice $container;

    public function __construct(string $message, int $statusCode, OrderNotEligibleForInvoice $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}