<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Models\Components;
use Polar\Utils\SpeakeasyMetadata;
class CustomerPortalSubscriptionsUpdateRequest
{
    /**
     * The subscription ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var Components\CustomerSubscriptionUpdatePrice|Components\CustomerSubscriptionCancel $customerSubscriptionUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerSubscriptionUpdatePrice|Components\CustomerSubscriptionCancel $customerSubscriptionUpdate;

    /**
     * @param  string  $id
     * @param  Components\CustomerSubscriptionUpdatePrice|Components\CustomerSubscriptionCancel  $customerSubscriptionUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\CustomerSubscriptionUpdatePrice|Components\CustomerSubscriptionCancel $customerSubscriptionUpdate)
    {
        $this->id = $id;
        $this->customerSubscriptionUpdate = $customerSubscriptionUpdate;
    }
}