<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Models\Components;
use Polar\Utils\SpeakeasyMetadata;
class CustomersUpdateRequest
{
    /**
     * The customer ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var Components\CustomerUpdate $customerUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerUpdate $customerUpdate;

    /**
     * Include members in the response. Only populated when set to true.
     *
     * @var ?bool $includeMembers
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include_members')]
    public ?bool $includeMembers = null;

    /**
     * @param  string  $id
     * @param  Components\CustomerUpdate  $customerUpdate
     * @param  ?bool  $includeMembers
     * @phpstan-pure
     */
    public function __construct(string $id, Components\CustomerUpdate $customerUpdate, ?bool $includeMembers = false)
    {
        $this->id = $id;
        $this->customerUpdate = $customerUpdate;
        $this->includeMembers = $includeMembers;
    }
}