<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Utils\SpeakeasyMetadata;
class CustomerPortalSeatsListSeatsRequest
{
    /**
     * Subscription ID
     *
     * @var string $subscriptionId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=subscription_id')]
    public string $subscriptionId;

    /**
     * @param  string  $subscriptionId
     * @phpstan-pure
     */
    public function __construct(string $subscriptionId)
    {
        $this->subscriptionId = $subscriptionId;
    }
}