<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Utils\SpeakeasyMetadata;
class CustomersMembersDeleteRequest
{
    /**
     * The customer ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var string $memberId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=member_id')]
    public string $memberId;

    /**
     * @param  string  $id
     * @param  string  $memberId
     * @phpstan-pure
     */
    public function __construct(string $id, string $memberId)
    {
        $this->id = $id;
        $this->memberId = $memberId;
    }
}