<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Models\Components;
use Polar\Utils\SpeakeasyMetadata;
class CustomersMembersUpdateExternalRequest
{
    /**
     * The customer external ID.
     *
     * @var string $externalId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=external_id')]
    public string $externalId;

    /**
     * The member external ID.
     *
     * @var string $memberExternalId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=member_external_id')]
    public string $memberExternalId;

    /**
     *
     * @var \Polar\Models\Components\MemberUpdate $memberUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\MemberUpdate $memberUpdate;

    /**
     * @param  string  $externalId
     * @param  string  $memberExternalId
     * @param  \Polar\Models\Components\MemberUpdate  $memberUpdate
     * @phpstan-pure
     */
    public function __construct(string $externalId, string $memberExternalId, Components\MemberUpdate $memberUpdate)
    {
        $this->externalId = $externalId;
        $this->memberExternalId = $memberExternalId;
        $this->memberUpdate = $memberUpdate;
    }
}