<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Models\Components;
use Polar\Utils\SpeakeasyMetadata;
class CustomersUpdateExternalRequest
{
    /**
     * The customer external ID.
     *
     * @var string $externalId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=external_id')]
    public string $externalId;

    /**
     *
     * @var Components\CustomerUpdate $customerUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerUpdate $customerUpdate;

    /**
     * @param  string  $externalId
     * @param  Components\CustomerUpdate  $customerUpdate
     * @phpstan-pure
     */
    public function __construct(string $externalId, Components\CustomerUpdate $customerUpdate)
    {
        $this->externalId = $externalId;
        $this->customerUpdate = $customerUpdate;
    }
}