<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Utils\SpeakeasyMetadata;
class CustomersMembersGetExternalRequest
{
    /**
     * The customer external ID.
     *
     * @var string $externalId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=external_id')]
    public string $externalId;

    /**
     * The member external ID.
     *
     * @var string $memberExternalId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=member_external_id')]
    public string $memberExternalId;

    /**
     * @param  string  $externalId
     * @param  string  $memberExternalId
     * @phpstan-pure
     */
    public function __construct(string $externalId, string $memberExternalId)
    {
        $this->externalId = $externalId;
        $this->memberExternalId = $memberExternalId;
    }
}