<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Models\Components;
use Polar\Utils\SpeakeasyMetadata;
class CustomersCreateRequest
{
    /**
     *
     * @var Components\CustomerCreate $customerCreate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerCreate $customerCreate;

    /**
     * Include members in the response. Only populated when set to true.
     *
     * @var ?bool $includeMembers
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include_members')]
    public ?bool $includeMembers = null;

    /**
     * @param  Components\CustomerCreate  $customerCreate
     * @param  ?bool  $includeMembers
     * @phpstan-pure
     */
    public function __construct(Components\CustomerCreate $customerCreate, ?bool $includeMembers = false)
    {
        $this->customerCreate = $customerCreate;
        $this->includeMembers = $includeMembers;
    }
}