<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Models\Components;
use Polar\Utils\SpeakeasyMetadata;
class CustomersMembersUpdateRequest
{
    /**
     * The customer ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var string $memberId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=member_id')]
    public string $memberId;

    /**
     *
     * @var \Polar\Models\Components\MemberUpdate $memberUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\MemberUpdate $memberUpdate;

    /**
     * @param  string  $id
     * @param  string  $memberId
     * @param  \Polar\Models\Components\MemberUpdate  $memberUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, string $memberId, Components\MemberUpdate $memberUpdate)
    {
        $this->id = $id;
        $this->memberId = $memberId;
        $this->memberUpdate = $memberUpdate;
    }
}