<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Models\Components;
use Polar\Utils\SpeakeasyMetadata;
class CustomerPortalCustomerMetersListRequest
{
    /**
     * Filter by meter ID.
     *
     * @var string|array<string>|null $meterId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=meter_id')]
    public string|array|null $meterId = null;

    /**
     * Filter by meter name.
     *
     * @var ?string $query
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=query')]
    public ?string $query = null;

    /**
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     *
     * @var ?array<Components\CustomerCustomerMeterSortProperty> $sorting
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sorting')]
    public ?array $sorting = null;

    /**
     * Page number, defaults to 1.
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     * Size of a page, defaults to 10. Maximum is 100.
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * @param  ?int  $page
     * @param  ?int  $limit
     * @param  string|array<string>|null  $meterId
     * @param  ?string  $query
     * @param  ?array<Components\CustomerCustomerMeterSortProperty>  $sorting
     * @phpstan-pure
     */
    public function __construct(string|array|null $meterId = null, ?string $query = null, ?array $sorting = null, ?int $page = 1, ?int $limit = 10)
    {
        $this->meterId = $meterId;
        $this->query = $query;
        $this->sorting = $sorting;
        $this->page = $page;
        $this->limit = $limit;
    }
}