<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class BalanceDisputeMetadata
{
    /**
     *
     * @var string $transactionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction_id')]
    public string $transactionId;

    /**
     *
     * @var string $disputeId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dispute_id')]
    public string $disputeId;

    /**
     *
     * @var int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public int $amount;

    /**
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     *
     * @var int $presentmentAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('presentment_amount')]
    public int $presentmentAmount;

    /**
     *
     * @var string $presentmentCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('presentment_currency')]
    public string $presentmentCurrency;

    /**
     *
     * @var int $taxAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_amount')]
    public int $taxAmount;

    /**
     *
     * @var int $fee
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fee')]
    public int $fee;

    /**
     *
     * @var ?string $orderId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('order_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $orderId = null;

    /**
     *
     * @var ?string $productId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $productId = null;

    /**
     *
     * @var ?string $subscriptionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subscriptionId = null;

    /**
     *
     * @var ?string $taxState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxState = null;

    /**
     *
     * @var ?string $taxCountry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_country')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxCountry = null;

    /**
     * @param  string  $transactionId
     * @param  string  $disputeId
     * @param  int  $amount
     * @param  string  $currency
     * @param  int  $presentmentAmount
     * @param  string  $presentmentCurrency
     * @param  int  $taxAmount
     * @param  int  $fee
     * @param  ?string  $orderId
     * @param  ?string  $productId
     * @param  ?string  $subscriptionId
     * @param  ?string  $taxState
     * @param  ?string  $taxCountry
     * @phpstan-pure
     */
    public function __construct(string $transactionId, string $disputeId, int $amount, string $currency, int $presentmentAmount, string $presentmentCurrency, int $taxAmount, int $fee, ?string $orderId = null, ?string $productId = null, ?string $subscriptionId = null, ?string $taxState = null, ?string $taxCountry = null)
    {
        $this->transactionId = $transactionId;
        $this->disputeId = $disputeId;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->presentmentAmount = $presentmentAmount;
        $this->presentmentCurrency = $presentmentCurrency;
        $this->taxAmount = $taxAmount;
        $this->fee = $fee;
        $this->orderId = $orderId;
        $this->productId = $productId;
        $this->subscriptionId = $subscriptionId;
        $this->taxState = $taxState;
        $this->taxCountry = $taxCountry;
    }
}