<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** BalanceDisputeReversalEvent - An event created by Polar when a dispute is won and funds are reinstated. */
class BalanceDisputeReversalEvent
{
    /**
     * The ID of the object.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The timestamp of the event.
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     * The ID of the organization owning the event.
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     * Human readable label of the event type.
     *
     * @var string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    public string $label;

    /**
     *
     * @var BalanceDisputeMetadata $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\BalanceDisputeMetadata')]
    public BalanceDisputeMetadata $metadata;

    /**
     * ID of the customer in your Polar organization associated with the event.
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    public ?string $customerId;

    /**
     * The customer associated with the event.
     *
     * @var ?Customer $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Customer|null')]
    public ?Customer $customer;

    /**
     * ID of the customer in your system associated with the event.
     *
     * @var ?string $externalCustomerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_customer_id')]
    public ?string $externalCustomerId;

    /**
     * The ID of the parent event.
     *
     * @var ?string $parentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parent_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $parentId = null;

    /**
     * The source of the event. `system` events are created by Polar. `user` events are the one you create through our ingestion API.
     *
     * @var string $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    public string $source;

    /**
     * The name of the event.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Number of direct child events linked to this event.
     *
     * @var ?int $childCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('child_count')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $childCount = null;

    /**
     * @param  string  $id
     * @param  \DateTime  $timestamp
     * @param  string  $organizationId
     * @param  string  $label
     * @param  string  $source
     * @param  string  $name
     * @param  BalanceDisputeMetadata  $metadata
     * @param  ?string  $customerId
     * @param  ?Customer  $customer
     * @param  ?string  $externalCustomerId
     * @param  ?int  $childCount
     * @param  ?string  $parentId
     * @phpstan-pure
     */
    public function __construct(string $id, \DateTime $timestamp, string $organizationId, string $label, BalanceDisputeMetadata $metadata, ?string $customerId = null, ?Customer $customer = null, ?string $externalCustomerId = null, ?string $parentId = null, string $source = 'system', string $name = 'balance.dispute_reversal', ?int $childCount = 0)
    {
        $this->id = $id;
        $this->timestamp = $timestamp;
        $this->organizationId = $organizationId;
        $this->label = $label;
        $this->metadata = $metadata;
        $this->customerId = $customerId;
        $this->customer = $customer;
        $this->externalCustomerId = $externalCustomerId;
        $this->parentId = $parentId;
        $this->source = $source;
        $this->name = $name;
        $this->childCount = $childCount;
    }
}