<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** BenefitFeatureFlagSubscriberProperties - Properties available to subscribers for a benefit of type `feature_flag`. */
class BenefitFeatureFlagSubscriberProperties
{

    public function __construct()
    {
    }
}