<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class BenefitGrantMeterCreditProperties
{
    /**
     *
     * @var string $lastCreditedMeterId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_credited_meter_id')]
    public string $lastCreditedMeterId;

    /**
     *
     * @var int $lastCreditedUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_credited_units')]
    public int $lastCreditedUnits;

    /**
     *
     * @var string $lastCreditedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_credited_at')]
    public string $lastCreditedAt;

    /**
     * @param  string  $lastCreditedMeterId
     * @param  int  $lastCreditedUnits
     * @param  string  $lastCreditedAt
     * @phpstan-pure
     */
    public function __construct(string $lastCreditedMeterId, int $lastCreditedUnits, string $lastCreditedAt)
    {
        $this->lastCreditedMeterId = $lastCreditedMeterId;
        $this->lastCreditedUnits = $lastCreditedUnits;
        $this->lastCreditedAt = $lastCreditedAt;
    }
}