<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CountAggregation
{
    /**
     *
     * @var ?string $func
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('func')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $func = null;

    /**
     * @param  ?string  $func
     * @phpstan-pure
     */
    public function __construct(?string $func = 'count')
    {
        $this->func = $func;
    }
}