<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CursorPagination
{
    /**
     *
     * @var bool $hasNextPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('has_next_page')]
    public bool $hasNextPage;

    /**
     * @param  bool  $hasNextPage
     * @phpstan-pure
     */
    public function __construct(bool $hasNextPage)
    {
        $this->hasNextPage = $hasNextPage;
    }
}