<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CustomerPortalCustomerSettings
{
    /**
     *
     * @var ?bool $allowEmailChange
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allow_email_change')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowEmailChange = null;

    /**
     * @param  ?bool  $allowEmailChange
     * @phpstan-pure
     */
    public function __construct(?bool $allowEmailChange = null)
    {
        $this->allowEmailChange = $allowEmailChange;
    }
}