<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CustomerBenefitGrantSlackSharedChannelUpdate
{
    /**
     *
     * @var \Polar\Models\Components\CustomerBenefitGrantSlackSharedChannelPropertiesUpdate $properties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('properties')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\CustomerBenefitGrantSlackSharedChannelPropertiesUpdate')]
    public CustomerBenefitGrantSlackSharedChannelPropertiesUpdate $properties;

    /**
     *
     * @var string $benefitType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('benefit_type')]
    public string $benefitType;

    /**
     * @param  string  $benefitType
     * @param  \Polar\Models\Components\CustomerBenefitGrantSlackSharedChannelPropertiesUpdate  $properties
     * @phpstan-pure
     */
    public function __construct(CustomerBenefitGrantSlackSharedChannelPropertiesUpdate $properties, string $benefitType = 'slack_shared_channel')
    {
        $this->properties = $properties;
        $this->benefitType = $benefitType;
    }
}