<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CustomerPortalCustomerUpdate
{
    /**
     *
     * @var ?string $billingName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingName = null;

    /**
     *
     * @var ?\Polar\Models\Components\AddressInput $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\AddressInput|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AddressInput $billingAddress = null;

    /**
     *
     * @var ?string $taxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxId = null;

    /**
     *
     * @var ?string $defaultPaymentMethodId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('default_payment_method_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $defaultPaymentMethodId = null;

    /**
     * @param  ?string  $billingName
     * @param  ?\Polar\Models\Components\AddressInput  $billingAddress
     * @param  ?string  $taxId
     * @param  ?string  $defaultPaymentMethodId
     * @phpstan-pure
     */
    public function __construct(?string $billingName = null, ?AddressInput $billingAddress = null, ?string $taxId = null, ?string $defaultPaymentMethodId = null)
    {
        $this->billingName = $billingName;
        $this->billingAddress = $billingAddress;
        $this->taxId = $taxId;
        $this->defaultPaymentMethodId = $defaultPaymentMethodId;
    }
}