<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CustomerSubscriptionUpdateClear
{
    /**
     * Clear the pending subscription update.
     *
     * @var mixed $pendingUpdate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pending_update')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $pendingUpdate;

    /**
     * @param  mixed  $pendingUpdate
     * @phpstan-pure
     */
    public function __construct(mixed $pendingUpdate = null)
    {
        $this->pendingUpdate = $pendingUpdate;
    }
}