<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CustomerSubscriptionUpdatePrice
{
    /**
     * Update subscription to another price.
     *
     * @var string $productPriceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_price_id')]
    public string $productPriceId;

    /**
     * @param  string  $productPriceId
     * @phpstan-pure
     */
    public function __construct(string $productPriceId)
    {
        $this->productPriceId = $productPriceId;
    }
}