<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum CustomerOrderSortProperty: string
{
    case CreatedAt = 'created_at';
    case MinusCreatedAt = '-created_at';
    case Amount = 'amount';
    case MinusAmount = '-amount';
    case NetAmount = 'net_amount';
    case MinusNetAmount = '-net_amount';
    case Product = 'product';
    case MinusProduct = '-product';
    case Subscription = 'subscription';
    case MinusSubscription = '-subscription';
}
