<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** CustomerStateMeter - An active meter for a customer, with latest consumed and credited units. */
class CustomerStateMeter
{
    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * The ID of the meter.
     *
     * @var string $meterId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meter_id')]
    public string $meterId;

    /**
     * The number of consumed units.
     *
     * @var float $consumedUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('consumed_units')]
    public float $consumedUnits;

    /**
     * The number of credited units.
     *
     * @var int $creditedUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('credited_units')]
    public int $creditedUnits;

    /**
     * The balance of the meter, i.e. the difference between credited and consumed units. Never goes negative.
     *
     * @var float $balance
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('balance')]
    public float $balance;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     * @param  \DateTime  $createdAt
     * @param  string  $meterId
     * @param  float  $consumedUnits
     * @param  int  $creditedUnits
     * @param  float  $balance
     * @param  ?\DateTime  $modifiedAt
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, string $meterId, float $consumedUnits, int $creditedUnits, float $balance, ?\DateTime $modifiedAt = null)
    {
        $this->createdAt = $createdAt;
        $this->meterId = $meterId;
        $this->consumedUnits = $consumedUnits;
        $this->creditedUnits = $creditedUnits;
        $this->balance = $balance;
        $this->modifiedAt = $modifiedAt;
    }
}