<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CustomerBenefitGrantSlackSharedChannelPropertiesUpdate
{
    /**
     *
     * @var string $invitedEmail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invited_email')]
    public string $invitedEmail;

    /**
     * @param  string  $invitedEmail
     * @phpstan-pure
     */
    public function __construct(string $invitedEmail)
    {
        $this->invitedEmail = $invitedEmail;
    }
}