<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CustomerEmailUpdateRequest
{
    /**
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     * @param  string  $email
     * @phpstan-pure
     */
    public function __construct(string $email)
    {
        $this->email = $email;
    }
}