<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum DisputeStatus: string
{
    case Prevented = 'prevented';
    case EarlyWarning = 'early_warning';
    case NeedsResponse = 'needs_response';
    case UnderReview = 'under_review';
    case Lost = 'lost';
    case Won = 'won';
}
