<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum Func: string
{
    case Sum = 'sum';
    case Max = 'max';
    case Min = 'min';
    case Avg = 'avg';
}
