<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** MemberUpdate - Schema for updating a member. */
class MemberUpdate
{
    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The role of the member within the customer.
     *
     * @var ?MemberRole $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\MemberRole|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MemberRole $role = null;

    /**
     * @param  ?string  $name
     * @param  ?MemberRole  $role
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?MemberRole $role = null)
    {
        $this->name = $name;
        $this->role = $role;
    }
}