<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class MeterQuantities
{
    /**
     * $quantities
     *
     * @var array<\Polar\Models\Components\MeterQuantity> $quantities
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantities')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\MeterQuantity>')]
    public array $quantities;

    /**
     * The total quantity for the period.
     *
     * @var float $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public float $total;

    /**
     * @param  array<\Polar\Models\Components\MeterQuantity>  $quantities
     * @param  float  $total
     * @phpstan-pure
     */
    public function __construct(array $quantities, float $total)
    {
        $this->quantities = $quantities;
        $this->total = $total;
    }
}