<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum MeterUnit: string
{
    case Scalar = 'scalar';
    case Token = 'token';
    case Custom = 'custom';
}
