<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class Metrics
{
    /**
     * Information about a metric.
     *
     * @var Metric $orders
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('orders')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $orders;

    /**
     * Information about a metric.
     *
     * @var Metric $revenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $revenue;

    /**
     * Information about a metric.
     *
     * @var Metric $netRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('net_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $netRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $cumulativeRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cumulative_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $cumulativeRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $netCumulativeRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('net_cumulative_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $netCumulativeRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $costs
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('costs')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $costs;

    /**
     * Information about a metric.
     *
     * @var Metric $cumulativeCosts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cumulative_costs')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $cumulativeCosts;

    /**
     * Information about a metric.
     *
     * @var Metric $averageOrderValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('average_order_value')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $averageOrderValue;

    /**
     * Information about a metric.
     *
     * @var Metric $netAverageOrderValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('net_average_order_value')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $netAverageOrderValue;

    /**
     * Information about a metric.
     *
     * @var Metric $averageRevenuePerUser
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('average_revenue_per_user')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $averageRevenuePerUser;

    /**
     * Information about a metric.
     *
     * @var Metric $costPerUser
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cost_per_user')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $costPerUser;

    /**
     * Information about a metric.
     *
     * @var Metric $activeUserByEvent
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active_user_by_event')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $activeUserByEvent;

    /**
     * Information about a metric.
     *
     * @var Metric $oneTimeProducts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('one_time_products')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $oneTimeProducts;

    /**
     * Information about a metric.
     *
     * @var Metric $oneTimeProductsRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('one_time_products_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $oneTimeProductsRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $oneTimeProductsNetRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('one_time_products_net_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $oneTimeProductsNetRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $newSubscriptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_subscriptions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $newSubscriptions;

    /**
     * Information about a metric.
     *
     * @var Metric $newSubscriptionsRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_subscriptions_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $newSubscriptionsRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $newSubscriptionsNetRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_subscriptions_net_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $newSubscriptionsNetRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $renewedSubscriptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('renewed_subscriptions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $renewedSubscriptions;

    /**
     * Information about a metric.
     *
     * @var Metric $renewedSubscriptionsRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('renewed_subscriptions_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $renewedSubscriptionsRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $renewedSubscriptionsNetRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('renewed_subscriptions_net_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $renewedSubscriptionsNetRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $activeSubscriptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active_subscriptions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $activeSubscriptions;

    /**
     * Information about a metric.
     *
     * @var Metric $monthlyRecurringRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('monthly_recurring_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $monthlyRecurringRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $committedMonthlyRecurringRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('committed_monthly_recurring_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $committedMonthlyRecurringRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $checkouts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checkouts')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $checkouts;

    /**
     * Information about a metric.
     *
     * @var Metric $succeededCheckouts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('succeeded_checkouts')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $succeededCheckouts;

    /**
     * Information about a metric.
     *
     * @var Metric $checkoutsConversion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checkouts_conversion')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $checkoutsConversion;

    /**
     * Information about a metric.
     *
     * @var Metric $canceledSubscriptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canceled_subscriptions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $canceledSubscriptions;

    /**
     * Information about a metric.
     *
     * @var Metric $canceledSubscriptionsCustomerService
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canceled_subscriptions_customer_service')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $canceledSubscriptionsCustomerService;

    /**
     * Information about a metric.
     *
     * @var Metric $canceledSubscriptionsLowQuality
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canceled_subscriptions_low_quality')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $canceledSubscriptionsLowQuality;

    /**
     * Information about a metric.
     *
     * @var Metric $canceledSubscriptionsMissingFeatures
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canceled_subscriptions_missing_features')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $canceledSubscriptionsMissingFeatures;

    /**
     * Information about a metric.
     *
     * @var Metric $canceledSubscriptionsSwitchedService
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canceled_subscriptions_switched_service')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $canceledSubscriptionsSwitchedService;

    /**
     * Information about a metric.
     *
     * @var Metric $canceledSubscriptionsTooComplex
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canceled_subscriptions_too_complex')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $canceledSubscriptionsTooComplex;

    /**
     * Information about a metric.
     *
     * @var Metric $canceledSubscriptionsTooExpensive
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canceled_subscriptions_too_expensive')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $canceledSubscriptionsTooExpensive;

    /**
     * Information about a metric.
     *
     * @var Metric $canceledSubscriptionsUnused
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canceled_subscriptions_unused')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $canceledSubscriptionsUnused;

    /**
     * Information about a metric.
     *
     * @var Metric $canceledSubscriptionsOther
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canceled_subscriptions_other')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $canceledSubscriptionsOther;

    /**
     * Information about a metric.
     *
     * @var Metric $churnRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('churn_rate')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $churnRate;

    /**
     * Information about a metric.
     *
     * @var Metric $grossMargin
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('gross_margin')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $grossMargin;

    /**
     * Information about a metric.
     *
     * @var Metric $grossMarginPercentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('gross_margin_percentage')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $grossMarginPercentage;

    /**
     * Information about a metric.
     *
     * @var Metric $cashflow
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cashflow')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $cashflow;

    /**
     * @param  Metric  $orders
     * @param  Metric  $revenue
     * @param  Metric  $netRevenue
     * @param  Metric  $cumulativeRevenue
     * @param  Metric  $netCumulativeRevenue
     * @param  Metric  $costs
     * @param  Metric  $cumulativeCosts
     * @param  Metric  $averageOrderValue
     * @param  Metric  $netAverageOrderValue
     * @param  Metric  $averageRevenuePerUser
     * @param  Metric  $costPerUser
     * @param  Metric  $activeUserByEvent
     * @param  Metric  $oneTimeProducts
     * @param  Metric  $oneTimeProductsRevenue
     * @param  Metric  $oneTimeProductsNetRevenue
     * @param  Metric  $newSubscriptions
     * @param  Metric  $newSubscriptionsRevenue
     * @param  Metric  $newSubscriptionsNetRevenue
     * @param  Metric  $renewedSubscriptions
     * @param  Metric  $renewedSubscriptionsRevenue
     * @param  Metric  $renewedSubscriptionsNetRevenue
     * @param  Metric  $activeSubscriptions
     * @param  Metric  $monthlyRecurringRevenue
     * @param  Metric  $committedMonthlyRecurringRevenue
     * @param  Metric  $checkouts
     * @param  Metric  $succeededCheckouts
     * @param  Metric  $checkoutsConversion
     * @param  Metric  $canceledSubscriptions
     * @param  Metric  $canceledSubscriptionsCustomerService
     * @param  Metric  $canceledSubscriptionsLowQuality
     * @param  Metric  $canceledSubscriptionsMissingFeatures
     * @param  Metric  $canceledSubscriptionsSwitchedService
     * @param  Metric  $canceledSubscriptionsTooComplex
     * @param  Metric  $canceledSubscriptionsTooExpensive
     * @param  Metric  $canceledSubscriptionsUnused
     * @param  Metric  $canceledSubscriptionsOther
     * @param  Metric  $churnRate
     * @param  Metric  $grossMargin
     * @param  Metric  $grossMarginPercentage
     * @param  Metric  $cashflow
     * @phpstan-pure
     */
    public function __construct(Metric $orders, Metric $revenue, Metric $netRevenue, Metric $cumulativeRevenue, Metric $netCumulativeRevenue, Metric $costs, Metric $cumulativeCosts, Metric $averageOrderValue, Metric $netAverageOrderValue, Metric $averageRevenuePerUser, Metric $costPerUser, Metric $activeUserByEvent, Metric $oneTimeProducts, Metric $oneTimeProductsRevenue, Metric $oneTimeProductsNetRevenue, Metric $newSubscriptions, Metric $newSubscriptionsRevenue, Metric $newSubscriptionsNetRevenue, Metric $renewedSubscriptions, Metric $renewedSubscriptionsRevenue, Metric $renewedSubscriptionsNetRevenue, Metric $activeSubscriptions, Metric $monthlyRecurringRevenue, Metric $committedMonthlyRecurringRevenue, Metric $checkouts, Metric $succeededCheckouts, Metric $checkoutsConversion, Metric $canceledSubscriptions, Metric $canceledSubscriptionsCustomerService, Metric $canceledSubscriptionsLowQuality, Metric $canceledSubscriptionsMissingFeatures, Metric $canceledSubscriptionsSwitchedService, Metric $canceledSubscriptionsTooComplex, Metric $canceledSubscriptionsTooExpensive, Metric $canceledSubscriptionsUnused, Metric $canceledSubscriptionsOther, Metric $churnRate, Metric $grossMargin, Metric $grossMarginPercentage, Metric $cashflow)
    {
        $this->orders = $orders;
        $this->revenue = $revenue;
        $this->netRevenue = $netRevenue;
        $this->cumulativeRevenue = $cumulativeRevenue;
        $this->netCumulativeRevenue = $netCumulativeRevenue;
        $this->costs = $costs;
        $this->cumulativeCosts = $cumulativeCosts;
        $this->averageOrderValue = $averageOrderValue;
        $this->netAverageOrderValue = $netAverageOrderValue;
        $this->averageRevenuePerUser = $averageRevenuePerUser;
        $this->costPerUser = $costPerUser;
        $this->activeUserByEvent = $activeUserByEvent;
        $this->oneTimeProducts = $oneTimeProducts;
        $this->oneTimeProductsRevenue = $oneTimeProductsRevenue;
        $this->oneTimeProductsNetRevenue = $oneTimeProductsNetRevenue;
        $this->newSubscriptions = $newSubscriptions;
        $this->newSubscriptionsRevenue = $newSubscriptionsRevenue;
        $this->newSubscriptionsNetRevenue = $newSubscriptionsNetRevenue;
        $this->renewedSubscriptions = $renewedSubscriptions;
        $this->renewedSubscriptionsRevenue = $renewedSubscriptionsRevenue;
        $this->renewedSubscriptionsNetRevenue = $renewedSubscriptionsNetRevenue;
        $this->activeSubscriptions = $activeSubscriptions;
        $this->monthlyRecurringRevenue = $monthlyRecurringRevenue;
        $this->committedMonthlyRecurringRevenue = $committedMonthlyRecurringRevenue;
        $this->checkouts = $checkouts;
        $this->succeededCheckouts = $succeededCheckouts;
        $this->checkoutsConversion = $checkoutsConversion;
        $this->canceledSubscriptions = $canceledSubscriptions;
        $this->canceledSubscriptionsCustomerService = $canceledSubscriptionsCustomerService;
        $this->canceledSubscriptionsLowQuality = $canceledSubscriptionsLowQuality;
        $this->canceledSubscriptionsMissingFeatures = $canceledSubscriptionsMissingFeatures;
        $this->canceledSubscriptionsSwitchedService = $canceledSubscriptionsSwitchedService;
        $this->canceledSubscriptionsTooComplex = $canceledSubscriptionsTooComplex;
        $this->canceledSubscriptionsTooExpensive = $canceledSubscriptionsTooExpensive;
        $this->canceledSubscriptionsUnused = $canceledSubscriptionsUnused;
        $this->canceledSubscriptionsOther = $canceledSubscriptionsOther;
        $this->churnRate = $churnRate;
        $this->grossMargin = $grossMargin;
        $this->grossMarginPercentage = $grossMarginPercentage;
        $this->cashflow = $cashflow;
    }
}