<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class Metrics
{
    /**
     * Information about a metric.
     *
     * @var Metric $orders
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('orders')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $orders;

    /**
     * Information about a metric.
     *
     * @var Metric $revenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $revenue;

    /**
     * Information about a metric.
     *
     * @var Metric $netRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('net_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $netRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $cumulativeRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cumulative_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $cumulativeRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $netCumulativeRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('net_cumulative_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $netCumulativeRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $averageOrderValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('average_order_value')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $averageOrderValue;

    /**
     * Information about a metric.
     *
     * @var Metric $netAverageOrderValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('net_average_order_value')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $netAverageOrderValue;

    /**
     * Information about a metric.
     *
     * @var Metric $oneTimeProducts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('one_time_products')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $oneTimeProducts;

    /**
     * Information about a metric.
     *
     * @var Metric $oneTimeProductsRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('one_time_products_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $oneTimeProductsRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $oneTimeProductsNetRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('one_time_products_net_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $oneTimeProductsNetRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $newSubscriptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_subscriptions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $newSubscriptions;

    /**
     * Information about a metric.
     *
     * @var Metric $newSubscriptionsRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_subscriptions_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $newSubscriptionsRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $newSubscriptionsNetRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_subscriptions_net_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $newSubscriptionsNetRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $renewedSubscriptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('renewed_subscriptions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $renewedSubscriptions;

    /**
     * Information about a metric.
     *
     * @var Metric $renewedSubscriptionsRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('renewed_subscriptions_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $renewedSubscriptionsRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $renewedSubscriptionsNetRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('renewed_subscriptions_net_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $renewedSubscriptionsNetRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $activeSubscriptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active_subscriptions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $activeSubscriptions;

    /**
     * Information about a metric.
     *
     * @var Metric $monthlyRecurringRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('monthly_recurring_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $monthlyRecurringRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $committedMonthlyRecurringRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('committed_monthly_recurring_revenue')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $committedMonthlyRecurringRevenue;

    /**
     * Information about a metric.
     *
     * @var Metric $checkouts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checkouts')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $checkouts;

    /**
     * Information about a metric.
     *
     * @var Metric $succeededCheckouts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('succeeded_checkouts')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $succeededCheckouts;

    /**
     * Information about a metric.
     *
     * @var Metric $checkoutsConversion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checkouts_conversion')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metric')]
    public Metric $checkoutsConversion;

    /**
     * @param  Metric  $orders
     * @param  Metric  $revenue
     * @param  Metric  $netRevenue
     * @param  Metric  $cumulativeRevenue
     * @param  Metric  $netCumulativeRevenue
     * @param  Metric  $averageOrderValue
     * @param  Metric  $netAverageOrderValue
     * @param  Metric  $oneTimeProducts
     * @param  Metric  $oneTimeProductsRevenue
     * @param  Metric  $oneTimeProductsNetRevenue
     * @param  Metric  $newSubscriptions
     * @param  Metric  $newSubscriptionsRevenue
     * @param  Metric  $newSubscriptionsNetRevenue
     * @param  Metric  $renewedSubscriptions
     * @param  Metric  $renewedSubscriptionsRevenue
     * @param  Metric  $renewedSubscriptionsNetRevenue
     * @param  Metric  $activeSubscriptions
     * @param  Metric  $monthlyRecurringRevenue
     * @param  Metric  $committedMonthlyRecurringRevenue
     * @param  Metric  $checkouts
     * @param  Metric  $succeededCheckouts
     * @param  Metric  $checkoutsConversion
     * @phpstan-pure
     */
    public function __construct(Metric $orders, Metric $revenue, Metric $netRevenue, Metric $cumulativeRevenue, Metric $netCumulativeRevenue, Metric $averageOrderValue, Metric $netAverageOrderValue, Metric $oneTimeProducts, Metric $oneTimeProductsRevenue, Metric $oneTimeProductsNetRevenue, Metric $newSubscriptions, Metric $newSubscriptionsRevenue, Metric $newSubscriptionsNetRevenue, Metric $renewedSubscriptions, Metric $renewedSubscriptionsRevenue, Metric $renewedSubscriptionsNetRevenue, Metric $activeSubscriptions, Metric $monthlyRecurringRevenue, Metric $committedMonthlyRecurringRevenue, Metric $checkouts, Metric $succeededCheckouts, Metric $checkoutsConversion)
    {
        $this->orders = $orders;
        $this->revenue = $revenue;
        $this->netRevenue = $netRevenue;
        $this->cumulativeRevenue = $cumulativeRevenue;
        $this->netCumulativeRevenue = $netCumulativeRevenue;
        $this->averageOrderValue = $averageOrderValue;
        $this->netAverageOrderValue = $netAverageOrderValue;
        $this->oneTimeProducts = $oneTimeProducts;
        $this->oneTimeProductsRevenue = $oneTimeProductsRevenue;
        $this->oneTimeProductsNetRevenue = $oneTimeProductsNetRevenue;
        $this->newSubscriptions = $newSubscriptions;
        $this->newSubscriptionsRevenue = $newSubscriptionsRevenue;
        $this->newSubscriptionsNetRevenue = $newSubscriptionsNetRevenue;
        $this->renewedSubscriptions = $renewedSubscriptions;
        $this->renewedSubscriptionsRevenue = $renewedSubscriptionsRevenue;
        $this->renewedSubscriptionsNetRevenue = $renewedSubscriptionsNetRevenue;
        $this->activeSubscriptions = $activeSubscriptions;
        $this->monthlyRecurringRevenue = $monthlyRecurringRevenue;
        $this->committedMonthlyRecurringRevenue = $committedMonthlyRecurringRevenue;
        $this->checkouts = $checkouts;
        $this->succeededCheckouts = $succeededCheckouts;
        $this->checkoutsConversion = $checkoutsConversion;
    }
}