<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class Order
{
    /**
     * The ID of the object.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     *
     * @var OrderStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\OrderStatus')]
    public OrderStatus $status;

    /**
     * Whether the order has been paid for.
     *
     * @var bool $paid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paid')]
    public bool $paid;

    /**
     * Amount in cents, before discounts and taxes.
     *
     * @var int $subtotalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotal_amount')]
    public int $subtotalAmount;

    /**
     * Discount amount in cents.
     *
     * @var int $discountAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_amount')]
    public int $discountAmount;

    /**
     * Amount in cents, after discounts but before taxes.
     *
     * @var int $netAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('net_amount')]
    public int $netAmount;

    /**
     * Amount in cents, after discounts but before taxes.
     *
     * @var int $amount
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public int $amount;

    /**
     * Sales tax amount in cents.
     *
     * @var int $taxAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_amount')]
    public int $taxAmount;

    /**
     * Amount in cents, after discounts and taxes.
     *
     * @var int $totalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_amount')]
    public int $totalAmount;

    /**
     * Amount refunded in cents.
     *
     * @var int $refundedAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refunded_amount')]
    public int $refundedAmount;

    /**
     * Sales tax refunded in cents.
     *
     * @var int $refundedTaxAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refunded_tax_amount')]
    public int $refundedTaxAmount;

    /**
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     *
     * @var OrderBillingReason $billingReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_reason')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\OrderBillingReason')]
    public OrderBillingReason $billingReason;

    /**
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    public string $customerId;

    /**
     *
     * @var string $productId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_id')]
    public string $productId;

    /**
     * $metadata
     *
     * @var array<string, string|int|float|bool> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string|int|float|bool>')]
    public array $metadata;

    /**
     *
     * @var OrderCustomer $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\OrderCustomer')]
    public OrderCustomer $customer;

    /**
     *
     * @var string $userId
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('user_id')]
    public string $userId;

    /**
     *
     * @var OrderProduct $product
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\OrderProduct')]
    public OrderProduct $product;

    /**
     * Line items composing the order.
     *
     * @var array<OrderItemSchema> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\OrderItemSchema>')]
    public array $items;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     *
     * @var ?Address $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Address|null')]
    public ?Address $billingAddress;

    /**
     *
     * @var ?string $discountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_id')]
    public ?string $discountId;

    /**
     *
     * @var ?string $subscriptionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription_id')]
    public ?string $subscriptionId;

    /**
     *
     * @var ?string $checkoutId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checkout_id')]
    public ?string $checkoutId;

    /**
     * Key-value object storing custom field values.
     *
     * @var ?array<string, string|int|bool|\DateTime|null> $customFieldData
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_field_data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string|int|bool|\DateTime|null>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $customFieldData = null;

    /**
     *
     * @var DiscountFixedOnceForeverDurationBase|DiscountFixedRepeatDurationBase|DiscountPercentageOnceForeverDurationBase|DiscountPercentageRepeatDurationBase|null $discount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\DiscountFixedOnceForeverDurationBase|\Polar\Models\Components\DiscountFixedRepeatDurationBase|\Polar\Models\Components\DiscountPercentageOnceForeverDurationBase|\Polar\Models\Components\DiscountPercentageRepeatDurationBase|null')]
    public DiscountFixedOnceForeverDurationBase|DiscountFixedRepeatDurationBase|DiscountPercentageOnceForeverDurationBase|DiscountPercentageRepeatDurationBase|null $discount;

    /**
     *
     * @var ?OrderSubscription $subscription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\OrderSubscription|null')]
    public ?OrderSubscription $subscription;

    /**
     * @param  string  $id
     * @param  \DateTime  $createdAt
     * @param  OrderStatus  $status
     * @param  bool  $paid
     * @param  int  $subtotalAmount
     * @param  int  $discountAmount
     * @param  int  $netAmount
     * @param  int  $amount
     * @param  int  $taxAmount
     * @param  int  $totalAmount
     * @param  int  $refundedAmount
     * @param  int  $refundedTaxAmount
     * @param  string  $currency
     * @param  OrderBillingReason  $billingReason
     * @param  string  $customerId
     * @param  string  $productId
     * @param  array<string, string|int|float|bool>  $metadata
     * @param  OrderCustomer  $customer
     * @param  string  $userId
     * @param  OrderProduct  $product
     * @param  array<OrderItemSchema>  $items
     * @param  ?\DateTime  $modifiedAt
     * @param  ?Address  $billingAddress
     * @param  ?string  $discountId
     * @param  ?string  $subscriptionId
     * @param  ?string  $checkoutId
     * @param  ?array<string, string|int|bool|\DateTime|null>  $customFieldData
     * @param  DiscountFixedOnceForeverDurationBase|DiscountFixedRepeatDurationBase|DiscountPercentageOnceForeverDurationBase|DiscountPercentageRepeatDurationBase|null  $discount
     * @param  ?OrderSubscription  $subscription
     * @phpstan-pure
     */
    public function __construct(string $id, \DateTime $createdAt, OrderStatus $status, bool $paid, int $subtotalAmount, int $discountAmount, int $netAmount, int $amount, int $taxAmount, int $totalAmount, int $refundedAmount, int $refundedTaxAmount, string $currency, OrderBillingReason $billingReason, string $customerId, string $productId, array $metadata, OrderCustomer $customer, string $userId, OrderProduct $product, array $items, ?\DateTime $modifiedAt = null, ?Address $billingAddress = null, ?string $discountId = null, ?string $subscriptionId = null, ?string $checkoutId = null, ?array $customFieldData = null, DiscountFixedOnceForeverDurationBase|DiscountFixedRepeatDurationBase|DiscountPercentageOnceForeverDurationBase|DiscountPercentageRepeatDurationBase|null $discount = null, ?OrderSubscription $subscription = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->status = $status;
        $this->paid = $paid;
        $this->subtotalAmount = $subtotalAmount;
        $this->discountAmount = $discountAmount;
        $this->netAmount = $netAmount;
        $this->amount = $amount;
        $this->taxAmount = $taxAmount;
        $this->totalAmount = $totalAmount;
        $this->refundedAmount = $refundedAmount;
        $this->refundedTaxAmount = $refundedTaxAmount;
        $this->currency = $currency;
        $this->billingReason = $billingReason;
        $this->customerId = $customerId;
        $this->productId = $productId;
        $this->metadata = $metadata;
        $this->customer = $customer;
        $this->userId = $userId;
        $this->product = $product;
        $this->items = $items;
        $this->modifiedAt = $modifiedAt;
        $this->billingAddress = $billingAddress;
        $this->discountId = $discountId;
        $this->subscriptionId = $subscriptionId;
        $this->checkoutId = $checkoutId;
        $this->customFieldData = $customFieldData;
        $this->discount = $discount;
        $this->subscription = $subscription;
    }
}