<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class OrderCustomer
{
    /**
     * The ID of the customer.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * $metadata
     *
     * @var array<string, string|int|float|bool> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string|int|float|bool>')]
    public array $metadata;

    /**
     * Whether the customer email address is verified. The address is automatically verified when the customer accesses the customer portal using their email address.
     *
     * @var bool $emailVerified
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email_verified')]
    public bool $emailVerified;

    /**
     *
     * @var \Polar\Models\Components\CustomerType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\CustomerType')]
    public CustomerType $type;

    /**
     * The ID of the organization owning the customer.
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     * The name of the customer.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public ?string $name;

    /**
     * The name that should appear on the customer's invoices. Falls back to the customer name when not explicitly set.
     *
     * @var ?string $billingName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_name')]
    public ?string $billingName;

    /**
     *
     * @var ?\Polar\Models\Components\Address $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Address|null')]
    public ?Address $billingAddress;

    /**
     * $taxId
     *
     * @var ?array<string|\Polar\Models\Components\TaxIDFormat|null> $taxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_id')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string|\Polar\Models\Components\TaxIDFormat|null>|null')]
    public ?array $taxId;

    /**
     * Timestamp for when the customer was soft deleted.
     *
     * @var ?\DateTime $deletedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deleted_at')]
    public ?\DateTime $deletedAt;

    /**
     *
     * @var ?string $avatarUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatar_url')]
    public ?string $avatarUrl;

    /**
     * The ID of the customer in your system. This must be unique within the organization. Once set, it can't be updated.
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     * The email address of the customer. This must be unique within the organization.
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     *
     * @var ?string $locale
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('locale')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $locale = null;

    /**
     * The ID of the customer's default payment method, if any. Use the payment methods endpoint to retrieve its details.
     *
     * @var ?string $defaultPaymentMethodId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('default_payment_method_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $defaultPaymentMethodId = null;

    /**
     * @param  string  $id
     * @param  \DateTime  $createdAt
     * @param  array<string, string|int|float|bool>  $metadata
     * @param  bool  $emailVerified
     * @param  \Polar\Models\Components\CustomerType  $type
     * @param  string  $organizationId
     * @param  ?\DateTime  $modifiedAt
     * @param  ?string  $name
     * @param  ?string  $billingName
     * @param  ?\Polar\Models\Components\Address  $billingAddress
     * @param  ?array<string|\Polar\Models\Components\TaxIDFormat|null>  $taxId
     * @param  ?\DateTime  $deletedAt
     * @param  ?string  $avatarUrl
     * @param  ?string  $externalId
     * @param  ?string  $email
     * @param  ?string  $locale
     * @param  ?string  $defaultPaymentMethodId
     * @phpstan-pure
     */
    public function __construct(string $id, \DateTime $createdAt, array $metadata, bool $emailVerified, CustomerType $type, string $organizationId, ?\DateTime $modifiedAt = null, ?string $name = null, ?string $billingName = null, ?Address $billingAddress = null, ?array $taxId = null, ?\DateTime $deletedAt = null, ?string $avatarUrl = null, ?string $externalId = null, ?string $email = null, ?string $locale = null, ?string $defaultPaymentMethodId = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->metadata = $metadata;
        $this->emailVerified = $emailVerified;
        $this->type = $type;
        $this->organizationId = $organizationId;
        $this->modifiedAt = $modifiedAt;
        $this->name = $name;
        $this->billingName = $billingName;
        $this->billingAddress = $billingAddress;
        $this->taxId = $taxId;
        $this->deletedAt = $deletedAt;
        $this->avatarUrl = $avatarUrl;
        $this->externalId = $externalId;
        $this->email = $email;
        $this->locale = $locale;
        $this->defaultPaymentMethodId = $defaultPaymentMethodId;
    }
}