<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** OrderUpdate - Schema to update an order. */
class OrderUpdate
{
    /**
     * The name of the customer that should appear on the invoice. Can't be updated after the invoice is generated.
     *
     * @var ?string $billingName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_name')]
    public ?string $billingName;

    /**
     * The address of the customer that should appear on the invoice. Can't be updated after the invoice is generated.
     *
     * @var ?AddressInput $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\AddressInput|null')]
    public ?AddressInput $billingAddress;

    /**
     * @param  ?string  $billingName
     * @param  ?AddressInput  $billingAddress
     * @phpstan-pure
     */
    public function __construct(?string $billingName = null, ?AddressInput $billingAddress = null)
    {
        $this->billingName = $billingName;
        $this->billingAddress = $billingAddress;
    }
}