<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class OrganizationNotificationSettings
{
    /**
     *
     * @var bool $newOrder
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_order')]
    public bool $newOrder;

    /**
     *
     * @var bool $newSubscription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_subscription')]
    public bool $newSubscription;

    /**
     * @param  bool  $newOrder
     * @param  bool  $newSubscription
     * @phpstan-pure
     */
    public function __construct(bool $newOrder, bool $newSubscription)
    {
        $this->newOrder = $newOrder;
        $this->newSubscription = $newSubscription;
    }
}