<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum OrganizationAccessTokenSortProperty: string
{
    case CreatedAt = 'created_at';
    case MinusCreatedAt = '-created_at';
    case Comment = 'comment';
    case MinusComment = '-comment';
    case LastUsedAt = 'last_used_at';
    case MinusLastUsedAt = '-last_used_at';
    case OrganizationId = 'organization_id';
    case MinusOrganizationId = '-organization_id';
}
