<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum OrganizationStatus: string
{
    case Created = 'created';
    case OnboardingStarted = 'onboarding_started';
    case UnderReview = 'under_review';
    case Denied = 'denied';
    case Active = 'active';
}
