<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum PresentmentCurrency: string
{
    case Aud = 'aud';
    case Brl = 'brl';
    case Cad = 'cad';
    case Chf = 'chf';
    case Eur = 'eur';
    case Inr = 'inr';
    case Gbp = 'gbp';
    case Jpy = 'jpy';
    case Sek = 'sek';
    case Usd = 'usd';
}
