<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** ProductPriceSeatBasedCreate - Schema to create a seat-based price with volume-based tiers. */
class ProductPriceSeatBasedCreate
{
    /**
     * List of pricing tiers for seat-based pricing.
     *
     * @var ProductPriceSeatTiers $seatTiers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('seat_tiers')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\ProductPriceSeatTiers')]
    public ProductPriceSeatTiers $seatTiers;

    /**
     *
     * @var string $amountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_type')]
    public string $amountType;

    /**
     * The currency. Currently, only `usd` is supported.
     *
     * @var ?string $priceCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $priceCurrency = null;

    /**
     * @param  string  $amountType
     * @param  ProductPriceSeatTiers  $seatTiers
     * @param  ?string  $priceCurrency
     * @phpstan-pure
     */
    public function __construct(ProductPriceSeatTiers $seatTiers, string $amountType = 'seat_based', ?string $priceCurrency = 'usd')
    {
        $this->seatTiers = $seatTiers;
        $this->amountType = $amountType;
        $this->priceCurrency = $priceCurrency;
    }
}