<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** ProductPriceSeatTiers - List of pricing tiers for seat-based pricing. */
class ProductPriceSeatTiers
{
    /**
     * List of pricing tiers
     *
     * @var array<ProductPriceSeatTier> $tiers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tiers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\ProductPriceSeatTier>')]
    public array $tiers;

    /**
     * @param  array<ProductPriceSeatTier>  $tiers
     * @phpstan-pure
     */
    public function __construct(array $tiers)
    {
        $this->tiers = $tiers;
    }
}