<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** ProductPriceFreeCreate - Schema to create a free price. */
class ProductPriceFreeCreate
{
    /**
     *
     * @var string $amountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_type')]
    public string $amountType;

    /**
     * @param  string  $amountType
     * @phpstan-pure
     */
    public function __construct(string $amountType = 'free')
    {
        $this->amountType = $amountType;
    }
}