<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** ProductPriceMeter - A meter associated to a metered price. */
class ProductPriceMeter
{
    /**
     * The ID of the object.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The name of the meter.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var \Polar\Models\Components\MeterUnit $unit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unit')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\MeterUnit')]
    public MeterUnit $unit;

    /**
     * The label for the custom unit.
     *
     * @var ?string $customLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customLabel = null;

    /**
     * The multiplier to convert from base unit to display scale.
     *
     * @var ?int $customMultiplier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_multiplier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $customMultiplier = null;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  \Polar\Models\Components\MeterUnit  $unit
     * @param  ?string  $customLabel
     * @param  ?int  $customMultiplier
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, MeterUnit $unit, ?string $customLabel = null, ?int $customMultiplier = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->unit = $unit;
        $this->customLabel = $customLabel;
        $this->customMultiplier = $customMultiplier;
    }
}