<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class ProductCreateRecurring
{
    /**
     * The name of the product.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * List of available prices for this product. It should contain at most one static price (fixed, custom or free), and any number of metered prices. Metered prices are not supported on one-time purchase products.
     *
     * @var array<ProductPriceFixedCreate|ProductPriceCustomCreate|ProductPriceFreeCreate|ProductPriceSeatBasedCreate|ProductPriceMeteredUnitCreate> $prices
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('prices')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\ProductPriceFixedCreate|\Polar\Models\Components\ProductPriceCustomCreate|\Polar\Models\Components\ProductPriceFreeCreate|\Polar\Models\Components\ProductPriceSeatBasedCreate|\Polar\Models\Components\ProductPriceMeteredUnitCreate>')]
    public array $prices;

    /**
     *
     * @var SubscriptionRecurringInterval $recurringInterval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurring_interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\SubscriptionRecurringInterval')]
    public SubscriptionRecurringInterval $recurringInterval;

    /**
     * Key-value object allowing you to store additional information.
     *
     *
     * The key must be a string with a maximum length of **40 characters**.
     * The value must be either:
     *
     * * A string with a maximum length of **500 characters**
     * * An integer
     * * A floating-point number
     * * A boolean
     *
     * You can store up to **50 key-value pairs**.
     *
     * @var ?array<string, string|int|float|bool> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string|int|float|bool>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * List of custom fields to attach.
     *
     * @var ?array<AttachedCustomFieldCreate> $attachedCustomFields
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attached_custom_fields')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\AttachedCustomFieldCreate>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $attachedCustomFields = null;

    /**
     * The description of the product.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * List of file IDs. Each one must be on the same organization as the product, of type `product_media` and correctly uploaded.
     *
     * @var ?array<string> $medias
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('medias')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $medias = null;

    /**
     * The ID of the organization owning the product. **Required unless you use an organization token.**
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organizationId = null;

    /**
     * The interval unit for the trial period.
     *
     * @var ?TrialInterval $trialInterval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('trial_interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\TrialInterval|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TrialInterval $trialInterval = null;

    /**
     * The number of interval units for the trial period.
     *
     * @var ?int $trialIntervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('trial_interval_count')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $trialIntervalCount = null;

    /**
     * Number of interval units of the subscription. If this is set to 1 the charge will happen every interval (e.g. every month), if set to 2 it will be every other month, and so on.
     *
     * @var ?int $recurringIntervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurring_interval_count')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $recurringIntervalCount = null;

    /**
     * @param  string  $name
     * @param  array<ProductPriceFixedCreate|ProductPriceCustomCreate|ProductPriceFreeCreate|ProductPriceSeatBasedCreate|ProductPriceMeteredUnitCreate>  $prices
     * @param  SubscriptionRecurringInterval  $recurringInterval
     * @param  ?array<string, string|int|float|bool>  $metadata
     * @param  ?array<AttachedCustomFieldCreate>  $attachedCustomFields
     * @param  ?int  $recurringIntervalCount
     * @param  ?string  $description
     * @param  ?array<string>  $medias
     * @param  ?string  $organizationId
     * @param  ?TrialInterval  $trialInterval
     * @param  ?int  $trialIntervalCount
     * @phpstan-pure
     */
    public function __construct(string $name, array $prices, SubscriptionRecurringInterval $recurringInterval, ?array $metadata = null, ?array $attachedCustomFields = null, ?string $description = null, ?array $medias = null, ?string $organizationId = null, ?TrialInterval $trialInterval = null, ?int $trialIntervalCount = null, ?int $recurringIntervalCount = 1)
    {
        $this->name = $name;
        $this->prices = $prices;
        $this->recurringInterval = $recurringInterval;
        $this->metadata = $metadata;
        $this->attachedCustomFields = $attachedCustomFields;
        $this->description = $description;
        $this->medias = $medias;
        $this->organizationId = $organizationId;
        $this->trialInterval = $trialInterval;
        $this->trialIntervalCount = $trialIntervalCount;
        $this->recurringIntervalCount = $recurringIntervalCount;
    }
}