<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** ProductPriceFreeCreate - Schema to create a free price. */
class ProductPriceFreeCreate
{
    /**
     *
     * @var ?\Polar\Models\Components\PresentmentCurrency $priceCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\PresentmentCurrency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PresentmentCurrency $priceCurrency = null;

    /**
     * The tax behavior of the price. If not set, it will default to the organization's default tax behavior.
     *
     * @var ?\Polar\Models\Components\TaxBehaviorOption $taxBehavior
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_behavior')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\TaxBehaviorOption|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TaxBehaviorOption $taxBehavior = null;

    /**
     *
     * @var string $amountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_type')]
    public string $amountType;

    /**
     * @param  string  $amountType
     * @param  ?\Polar\Models\Components\PresentmentCurrency  $priceCurrency
     * @param  ?\Polar\Models\Components\TaxBehaviorOption  $taxBehavior
     * @phpstan-pure
     */
    public function __construct(?PresentmentCurrency $priceCurrency = null, ?TaxBehaviorOption $taxBehavior = null, string $amountType = 'free')
    {
        $this->priceCurrency = $priceCurrency;
        $this->taxBehavior = $taxBehavior;
        $this->amountType = $amountType;
    }
}