<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** Product - A product. */
class Product
{
    /**
     * The ID of the object.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * The name of the product.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Whether the product is a subscription.
     *
     * @var bool $isRecurring
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_recurring')]
    public bool $isRecurring;

    /**
     * Whether the product is archived and no longer available.
     *
     * @var bool $isArchived
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_archived')]
    public bool $isArchived;

    /**
     * The ID of the organization owning the product.
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     * $metadata
     *
     * @var array<string, string|int|float|bool> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string|int|float|bool>')]
    public array $metadata;

    /**
     * List of prices for this product.
     *
     * @var array<LegacyRecurringProductPriceFixed|LegacyRecurringProductPriceCustom|LegacyRecurringProductPriceFree|ProductPriceFixed|ProductPriceCustom|ProductPriceFree|ProductPriceSeatBased|ProductPriceMeteredUnit> $prices
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('prices')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\LegacyRecurringProductPriceFixed|\Polar\Models\Components\LegacyRecurringProductPriceCustom|\Polar\Models\Components\LegacyRecurringProductPriceFree|\Polar\Models\Components\ProductPriceFixed|\Polar\Models\Components\ProductPriceCustom|\Polar\Models\Components\ProductPriceFree|\Polar\Models\Components\ProductPriceSeatBased|\Polar\Models\Components\ProductPriceMeteredUnit>')]
    public array $prices;

    /**
     * List of benefits granted by the product.
     *
     * @var array<BenefitCustom|BenefitDiscord|BenefitGitHubRepository|BenefitDownloadables|BenefitLicenseKeys|BenefitMeterCredit> $benefits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('benefits')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\BenefitCustom|\Polar\Models\Components\BenefitDiscord|\Polar\Models\Components\BenefitGitHubRepository|\Polar\Models\Components\BenefitDownloadables|\Polar\Models\Components\BenefitLicenseKeys|\Polar\Models\Components\BenefitMeterCredit>')]
    public array $benefits;

    /**
     * List of medias associated to the product.
     *
     * @var array<ProductMediaFileRead> $medias
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('medias')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\ProductMediaFileRead>')]
    public array $medias;

    /**
     * List of custom fields attached to the product.
     *
     * @var array<AttachedCustomField> $attachedCustomFields
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attached_custom_fields')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\AttachedCustomField>')]
    public array $attachedCustomFields;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     * The interval unit for the trial period.
     *
     * @var ?TrialInterval $trialInterval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('trial_interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\TrialInterval|null')]
    public ?TrialInterval $trialInterval;

    /**
     * The number of interval units for the trial period.
     *
     * @var ?int $trialIntervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('trial_interval_count')]
    public ?int $trialIntervalCount;

    /**
     * The description of the product.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public ?string $description;

    /**
     * The recurring interval of the product. If `None`, the product is a one-time purchase.Note that the `day` and `week` values are for internal Polar staff use only.
     *
     * @var ?SubscriptionRecurringInterval $recurringInterval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurring_interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\SubscriptionRecurringInterval|null')]
    public ?SubscriptionRecurringInterval $recurringInterval;

    /**
     * @param  string  $id
     * @param  \DateTime  $createdAt
     * @param  string  $name
     * @param  bool  $isRecurring
     * @param  bool  $isArchived
     * @param  string  $organizationId
     * @param  array<string, string|int|float|bool>  $metadata
     * @param  array<LegacyRecurringProductPriceFixed|LegacyRecurringProductPriceCustom|LegacyRecurringProductPriceFree|ProductPriceFixed|ProductPriceCustom|ProductPriceFree|ProductPriceSeatBased|ProductPriceMeteredUnit>  $prices
     * @param  array<BenefitCustom|BenefitDiscord|BenefitGitHubRepository|BenefitDownloadables|BenefitLicenseKeys|BenefitMeterCredit>  $benefits
     * @param  array<ProductMediaFileRead>  $medias
     * @param  array<AttachedCustomField>  $attachedCustomFields
     * @param  ?\DateTime  $modifiedAt
     * @param  ?TrialInterval  $trialInterval
     * @param  ?int  $trialIntervalCount
     * @param  ?string  $description
     * @param  ?SubscriptionRecurringInterval  $recurringInterval
     * @phpstan-pure
     */
    public function __construct(string $id, \DateTime $createdAt, string $name, bool $isRecurring, bool $isArchived, string $organizationId, array $metadata, array $prices, array $benefits, array $medias, array $attachedCustomFields, ?\DateTime $modifiedAt = null, ?TrialInterval $trialInterval = null, ?int $trialIntervalCount = null, ?string $description = null, ?SubscriptionRecurringInterval $recurringInterval = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->name = $name;
        $this->isRecurring = $isRecurring;
        $this->isArchived = $isArchived;
        $this->organizationId = $organizationId;
        $this->metadata = $metadata;
        $this->prices = $prices;
        $this->benefits = $benefits;
        $this->medias = $medias;
        $this->attachedCustomFields = $attachedCustomFields;
        $this->modifiedAt = $modifiedAt;
        $this->trialInterval = $trialInterval;
        $this->trialIntervalCount = $trialIntervalCount;
        $this->description = $description;
        $this->recurringInterval = $recurringInterval;
    }
}