<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** ProductPriceFixed - A fixed price for a product. */
class ProductPriceFixed
{
    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * The ID of the price.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var ProductPriceSource $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\ProductPriceSource')]
    public ProductPriceSource $source;

    /**
     * Whether the price is archived and no longer available.
     *
     * @var bool $isArchived
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_archived')]
    public bool $isArchived;

    /**
     * The ID of the product owning the price.
     *
     * @var string $productId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_id')]
    public string $productId;

    /**
     *
     * @var ProductPriceType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\ProductPriceType')]
    public ProductPriceType $type;

    /**
     * The currency.
     *
     * @var string $priceCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_currency')]
    public string $priceCurrency;

    /**
     * The price in cents.
     *
     * @var int $priceAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_amount')]
    public int $priceAmount;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     *
     * @var ?SubscriptionRecurringInterval $recurringInterval
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurring_interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\SubscriptionRecurringInterval|null')]
    public ?SubscriptionRecurringInterval $recurringInterval;

    /**
     *
     * @var string $amountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_type')]
    public string $amountType;

    /**
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  ProductPriceSource  $source
     * @param  string  $amountType
     * @param  bool  $isArchived
     * @param  string  $productId
     * @param  ProductPriceType  $type
     * @param  string  $priceCurrency
     * @param  int  $priceAmount
     * @param  ?\DateTime  $modifiedAt
     * @param  ?SubscriptionRecurringInterval  $recurringInterval
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, string $id, ProductPriceSource $source, bool $isArchived, string $productId, ProductPriceType $type, string $priceCurrency, int $priceAmount, ?\DateTime $modifiedAt = null, ?SubscriptionRecurringInterval $recurringInterval = null, string $amountType = 'fixed')
    {
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->source = $source;
        $this->isArchived = $isArchived;
        $this->productId = $productId;
        $this->type = $type;
        $this->priceCurrency = $priceCurrency;
        $this->priceAmount = $priceAmount;
        $this->modifiedAt = $modifiedAt;
        $this->recurringInterval = $recurringInterval;
        $this->amountType = $amountType;
    }
}