<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum PublicSubscriptionProrationBehavior: string
{
    case Invoice = 'invoice';
    case Prorate = 'prorate';
    case NextPeriod = 'next_period';
}
