<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class SubscriptionPausedMetadata
{
    /**
     *
     * @var string $subscriptionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription_id')]
    public string $subscriptionId;

    /**
     *
     * @var string $pausedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paused_at')]
    public string $pausedAt;

    /**
     *
     * @var ?string $productId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $productId = null;

    /**
     *
     * @var ?int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $amount = null;

    /**
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     *
     * @var ?string $recurringInterval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurring_interval')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $recurringInterval = null;

    /**
     *
     * @var ?int $recurringIntervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurring_interval_count')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $recurringIntervalCount = null;

    /**
     *
     * @var ?string $resumesAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resumes_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $resumesAt = null;

    /**
     * @param  string  $subscriptionId
     * @param  string  $pausedAt
     * @param  ?string  $productId
     * @param  ?int  $amount
     * @param  ?string  $currency
     * @param  ?string  $recurringInterval
     * @param  ?int  $recurringIntervalCount
     * @param  ?string  $resumesAt
     * @phpstan-pure
     */
    public function __construct(string $subscriptionId, string $pausedAt, ?string $productId = null, ?int $amount = null, ?string $currency = null, ?string $recurringInterval = null, ?int $recurringIntervalCount = null, ?string $resumesAt = null)
    {
        $this->subscriptionId = $subscriptionId;
        $this->pausedAt = $pausedAt;
        $this->productId = $productId;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->recurringInterval = $recurringInterval;
        $this->recurringIntervalCount = $recurringIntervalCount;
        $this->resumesAt = $resumesAt;
    }
}