<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class SubscriptionUpdatedSeatsMetadata
{
    /**
     *
     * @var string $subscriptionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription_id')]
    public string $subscriptionId;

    /**
     *
     * @var int $seats
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('seats')]
    public int $seats;

    /**
     *
     * @var \Polar\Models\Components\SubscriptionProrationBehavior $prorationBehavior
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('proration_behavior')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\SubscriptionProrationBehavior')]
    public SubscriptionProrationBehavior $prorationBehavior;

    /**
     * @param  string  $subscriptionId
     * @param  int  $seats
     * @param  \Polar\Models\Components\SubscriptionProrationBehavior  $prorationBehavior
     * @phpstan-pure
     */
    public function __construct(string $subscriptionId, int $seats, SubscriptionProrationBehavior $prorationBehavior)
    {
        $this->subscriptionId = $subscriptionId;
        $this->seats = $seats;
        $this->prorationBehavior = $prorationBehavior;
    }
}