<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class SubscriptionUpdateProduct
{
    /**
     * Update subscription to another product.
     *
     * @var string $productId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_id')]
    public string $productId;

    /**
     * Determine how to handle the proration billing. If not provided, will use the default organization setting.
     *
     * @var ?SubscriptionProrationBehavior $prorationBehavior
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('proration_behavior')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\SubscriptionProrationBehavior|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SubscriptionProrationBehavior $prorationBehavior = null;

    /**
     * @param  string  $productId
     * @param  ?SubscriptionProrationBehavior  $prorationBehavior
     * @phpstan-pure
     */
    public function __construct(string $productId, ?SubscriptionProrationBehavior $prorationBehavior = null)
    {
        $this->productId = $productId;
        $this->prorationBehavior = $prorationBehavior;
    }
}