<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class ValidationError
{
    /**
     * $loc
     *
     * @var array<string|int> $loc
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('loc')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string|int>')]
    public array $loc;

    /**
     *
     * @var string $msg
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('msg')]
    public string $msg;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     *
     * @var mixed $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $input = null;

    /**
     *
     * @var ?Context $ctx
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ctx')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Context|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Context $ctx = null;

    /**
     * @param  array<string|int>  $loc
     * @param  string  $msg
     * @param  string  $type
     * @param  mixed  $input
     * @param  ?Context  $ctx
     * @phpstan-pure
     */
    public function __construct(array $loc, string $msg, string $type, mixed $input = null, ?Context $ctx = null)
    {
        $this->loc = $loc;
        $this->msg = $msg;
        $this->type = $type;
        $this->input = $input;
        $this->ctx = $ctx;
    }
}