<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/**
 * WebhookCheckoutCreatedPayload - Sent when a new checkout is created.
 *
 *
 * **Discord & Slack support:** Basic
 */
class WebhookCheckoutCreatedPayload
{
    /**
     * Checkout session data retrieved using an access token.
     *
     * @var Checkout $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Checkout')]
    public Checkout $data;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $type
     * @param  Checkout  $data
     * @phpstan-pure
     */
    public function __construct(Checkout $data, string $type = 'checkout.created')
    {
        $this->data = $data;
        $this->type = $type;
    }
}