<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/**
 * WebhookMemberUpdatedPayload - Sent when a member is updated.
 *
 *
 * This event is triggered when member details are updated,
 * such as their name or role within the customer.
 *
 * **Discord & Slack support:** Basic
 */
class WebhookMemberUpdatedPayload
{
    /**
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     * A member of a customer.
     *
     * @var \Polar\Models\Components\Member $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Member')]
    public Member $data;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $type
     * @param  \DateTime  $timestamp
     * @param  \Polar\Models\Components\Member  $data
     * @phpstan-pure
     */
    public function __construct(\DateTime $timestamp, Member $data, string $type = 'member.updated')
    {
        $this->timestamp = $timestamp;
        $this->data = $data;
        $this->type = $type;
    }
}